
export const DATA_LOADING = 'DATA_LOADING'

export const DATA_LOADING_SUCCESS = 'DATA_LOADING_SUCCESS'

export const DATA_LOADING_ERROR = 'DATA_LOADING_ERROR'

export const MODALS = 'MODALS'

export const CHANGE_PRIORITY = 'CHANGE_PRIORITY'

export const CHANGE_HEIGHT_LIST = 'CHANGE_HEIGHT_LIST'
